[project]
site_name = "oai2ollama"
site_description = "Wrap any OpenAI-compatible API into an Ollama-compatible API."
site_url = "https://oai2ollama.vercel.app"
repo_url = "https://github.com/CNSeniorious000/oai2ollama"
repo_name = "CNSeniorious000/oai2ollama"
site_author = "Muspi Merol"
extra_css = ["stylesheets/extra.css"]

[[project.extra.social]]
icon = "material/github"
link = "https://github.com/CNSeniorious000/oai2ollama"
name = "GitHub Repository"

[[project.extra.social]]
icon = "material/language-python"
link = "https://pypi.org/project/oai2ollama/"
name = "oai2ollama on PyPI"

[project.theme]
favicon = "https://ollama.com/public/apple-touch-icon.png"
custom_dir = "docs/overrides"
features = [
    "search.highlight",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.instant.prefetch",
    "navigation.sections",
    "navigation.footer",
    "navigation.top",
    "toc.integrate",
    "toc.follow",
    "content.code.copy",
    "content.code.annotate",
    "content.tooltips",
]

[project.theme.icon]
repo = "material/github"
logo = "lucide/blend"

[project.theme.font]
text = "Armata"
code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "lime"
accent = "lime"
toggle.icon = "material/lightbulb"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "teal"
toggle.icon = "material/lightbulb-outline"
toggle.name = "Switch to dark mode"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
options.custom_icons = ["docs"]
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tilde]

[project.plugins.mkdocstrings.handlers.python.options]
title_level = 3
line_length = 90
members_order = "source"
show_if_no_docstring = true
modernize_annotations = true
show_symbol_type_heading = true
overloads_only = true
show_signature_annotations = true
show_signature_type_parameters = true
separate_signature = true
filters = [".*"]
show_root_toc_entry = true
show_symbol_type_toc = true
show_root_heading = true
